name: slow-snap
version: git
summary: A slow snap
description: |
  very slow

grade: stable
confinement: strict
base: core18

apps:
  slow-snap:
    command: python3 -c "import os; import argparse; from autobahn.twisted.component import run"

parts:
  slow-snap:
    plugin: python
    python-packages:
      - autobahn[twisted]
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      $SNAPCRAFT_PART_INSTALL/usr/bin/python3 -m compileall -q $SNAPCRAFT_PRIME
