name: slow-snap
version: git
summary: A slow snap
description: |
  very slow

grade: stable
confinement: strict
base: core18

environment:
  PYTHONPATH: PYTHONPATH:$SNAP_COMMON/deskconnd-runtime-dir

apps:
  slow-snap:
    command: python3 -c "import os; import argparse; from autobahn.twisted.component import run"

parts:
  launcher:
    plugin: nil

plugs:
  deskconnd-runtime-dir:
    content: executables
    default-provider: deskconnd:runtime-dir
    interface: content
    target: $SNAP_COMMON/deskconnd-runtime-dir
